NAME = background
CC = g++
CFLAGS =   
#LIBS = -lopencv_video -lopencv_core -lopencv_highgui -lopencv_imgproc
#LPATH = -L/usr/local/lib 
LIBS = -L/usr/local/lib -lopencv_core -lopencv_highgui -lopencv_imgproc -lopencv_video
all:
	$(CC) $(NAME).cpp $(CFLAGS) $(LIBS) -o $(NAME)
